name: demostore
recipe: laravel

config:
  webroot: public
  php: '8.2'
  via: nginx
  cache: redis
  xdebug: false

services:
  database:
    portforward: 3306

  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

  node:
    type: node:20

tooling:
  npm:
    service: node
